on:
  push:
    branches:
      - master
name: Build Gatsby Site
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: echo 'tests shall come'

      - name: Build Site
        run: npm run build

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false terraform/

      - name: Terraform Validate
        id: validate
        run: terraform validate terraform/

      - name: Terraform Plan
        id: plan
        run: terraform plan -out "planfile" terraform/

      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false planfile

      # Finally, this is how we upload our build to our bucket
      - uses: chrislennon/action-aws-cli@v1.1
      - name: Sync to S3
        run: aws s3 sync public s3://kwhitejr.com
