on:
  push:
    branches:
      - master
name: Build Gatsby Site
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: DeployKwhitejrCom
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.4
          terraform_wrapper: false

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: echo 'tests shall come'

      - name: Build Site
        run: npm run build

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out "planfile"

      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false planfile

      # Finally, this is how we upload our build to our bucket
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ../public s3://$(terraform output s3_bucket) --delete
